# back to language cpp to try to bypass osx node failure
language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
deploy:
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: public
  provider: pages
  skip-cleanup: true
  target-branch: master
before_script:
  - npm i
script:
  - npm run test
after_success:
  - npm run deploy

