# back to language cpp to try to bypass osx node failure
language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
deploy:
  provider: surge
  project: ./public/
  domain: steveafrost.com
  skip_cleanup: true
before_script:
  - npm i
script:
  - npm run test
after_success:
  - npm run deploy

